export const ADD_TAG = 'ADD_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_OPTIONS_REQUEST = 'FETCH_OPTIONS_REQUEST';
export const FETCH_OPTIONS_SUCCESS = 'FETCH_OPTIONS_SUCCESS';
export const FETCH_OPTIONS_FAILURE = 'FETCH_OPTIONS_FAILURE';

export const UPDATE_FREQUENTLY_USED = 'UPDATE_FREQUENTLY_USED';
export const FETCH_FREQUENTLY_USED_REQUEST = 'FETCH_FREQUENTLY_USED_REQUEST';
export const FETCH_FREQUENTLY_USED_SUCCESS = 'FETCH_FREQUENTLY_USED_SUCCESS';
export const FETCH_FREQUENTLY_USED_FAILURE = 'FETCH_FREQUENTLY_USED_FAILURE';

