export const SETS_API_REQUEST = 'SETS_API_REQUEST';
export const SETS_API_SUCCESS = 'SETS_API_SUCCESS';
export const SETS_API_FAILURE = 'SETS_API_FAILURE';

export const USER_API_REQUEST = 'USER_API_REQUEST';
export const USER_API_SUCCESS = 'USER_API_SUCCESS';
export const USER_API_FAILURE = 'USER_API_FAILURE';

export const OPTIONS_API_REQUEST = 'OPTIONS_API_REQUEST';
export const OPTIONS_API_SUCCESS = 'OPTIONS_API_SUCCESS';
export const OPTIONS_API_FAILURE = 'OPTIONS_API_FAILURE';

export const FREQUENTLY_USED_API_REQUEST = 'FREQUENTLY_USED_API_REQUEST';
export const FREQUENTLY_USED_API_SUCCESS = 'FREQUENTLY_USED_API_SUCCESS';
export const FREQUENTLY_USED_API_FAILURE = 'FREQUENTLY_USED_API_FAILURE';
