export const frankerfacezSetData: {name: string, tags: { [_: string]: [string[], string, string?] }} = {
    "name": "FrakerFaceZ",
    "tags": {
        "AYAYA": [[], "https://cdn.frankerfacez.com/emoticon/162146/1"],
        "OMEGALUL": [[], "https://cdn.frankerfacez.com/emoticon/128054/1"],
        "LULW": [[], "https://cdn.frankerfacez.com/emoticon/139407/1"],
        "PepeHands": [[], "https://cdn.frankerfacez.com/emoticon/231552/1"],
        "PogU": [[], "https://cdn.frankerfacez.com/emoticon/256055/1"],
        "Pepega": [[], "https://cdn.frankerfacez.com/emoticon/243789/1"],
        "POGGERS": [[], "https://cdn.frankerfacez.com/emoticon/214129/1"],
        "monkaS": [[], "https://cdn.frankerfacez.com/emoticon/130762/1"],
        "Pog": [[], "https://cdn.frankerfacez.com/emoticon/210748/1"],
        "FeelsBadMan": [[], "https://cdn.frankerfacez.com/emoticon/33355/1"],
        "PepeLaugh": [[], "https://cdn.frankerfacez.com/emoticon/64785/1"],
        "PagChomp": [[], "https://cdn.frankerfacez.com/emoticon/61496/1"],
        "gachiGASM": [[], "https://cdn.frankerfacez.com/emoticon/103171/1"],
        "monkaW": [[], "https://cdn.frankerfacez.com/emoticon/214681/1"],
        "HandsUp": [[], "https://cdn.frankerfacez.com/emoticon/229760/1"],
        "WeirdChamp": [[], "https://cdn.frankerfacez.com/emoticon/262468/1"],
        "FeelsOkayMan": [[], "https://cdn.frankerfacez.com/emoticon/145947/1"],
        "5Head": [[], "https://cdn.frankerfacez.com/emoticon/239504/1"],
        // "HYPERBRUH": [[], "https://cdn.frankerfacez.com/emoticon/204717/1"],
        // "Kapp": [[], "https://cdn.frankerfacez.com/emoticon/218860/1"],
        // "FeelsWeirdMan": [[], "https://cdn.frankerfacez.com/emoticon/131597/1"],
        // "HYPERS": [[], "https://cdn.frankerfacez.com/emoticon/236895/1"],
        // "KKomrade": [[], "https://cdn.frankerfacez.com/emoticon/145916/1"],
        // "EZY": [[], "https://cdn.frankerfacez.com/emoticon/185890/1"],
        // "4HEad": [[], "https://cdn.frankerfacez.com/emoticon/128247/1"],
        // "PepoThink": [[], "https://cdn.frankerfacez.com/emoticon/174942/1"],
        // "3Head": [[], "https://cdn.frankerfacez.com/emoticon/274406/1"],
        // "monkaOMEGA": [[], "https://cdn.frankerfacez.com/emoticon/167431/1"],
        // "FeelsGoodMan": [[], "https://cdn.frankerfacez.com/emoticon/109777/1"],
        // "forsenCD": [[], "https://cdn.frankerfacez.com/emoticon/249060/1"],
        // "KEKW": [[], "https://cdn.frankerfacez.com/emoticon/381875/1"],
        // "monkaMEGA": [[], "https://cdn.frankerfacez.com/emoticon/157576/1"],
        // "monkaTOS": [[], "https://cdn.frankerfacez.com/emoticon/237857/1"],
        // "monkaGun": [[], "https://cdn.frankerfacez.com/emoticon/187256/1"],
        // "monkaHmm": [[], "https://cdn.frankerfacez.com/emoticon/240746/1"],
        // "weSmart": [[], "https://cdn.frankerfacez.com/emoticon/165742/1"],
        // "KKonaW": [[], "https://cdn.frankerfacez.com/emoticon/229486/1"],
        // "monkaH": [[], "https://cdn.frankerfacez.com/emoticon/201362/1"],
        // "OkayChamp": [[], "https://cdn.frankerfacez.com/emoticon/280358/1"],
        // "peepoHappy": [[], "https://cdn.frankerfacez.com/emoticon/228449/1"],
        // "4House": [[], "https://cdn.frankerfacez.com/emoticon/230495/1"],
        // "REEeee": [[], "https://cdn.frankerfacez.com/emoticon/116831/1"],
        // "FeelsSpecialMan": [[], "https://cdn.frankerfacez.com/emoticon/191854/1"],
        // "Klappa": [[], "https://cdn.frankerfacez.com/emoticon/38879/1"],
        // "HeavyBreathing": [[], "https://cdn.frankerfacez.com/emoticon/29990/1"],
        // "peepoSad": [[], "https://cdn.frankerfacez.com/emoticon/230082/1"],
        // "HYPERDANSGAME": [[], "https://cdn.frankerfacez.com/emoticon/261915/1"],
        // "ThisIsFine": [[], "https://cdn.frankerfacez.com/emoticon/67872/1"],
        // "JUSTDOIT": [[], "https://cdn.frankerfacez.com/emoticon/37311/1"],
        // "FeelsStrongMan": [[], "https://cdn.frankerfacez.com/emoticon/64210/1"],
        // "peepoBlanket": [[], "https://cdn.frankerfacez.com/emoticon/262458/1"],
        // "MaN": [[], "https://cdn.frankerfacez.com/emoticon/266564/1"],
        // "PogYou": [[], "https://cdn.frankerfacez.com/emoticon/297232/1"],
        // "gachiHYPER": [[], "https://cdn.frankerfacez.com/emoticon/196406/1"],
        // "Pogey": [[], "https://cdn.frankerfacez.com/emoticon/262805/1"],
        // "FeelsDankMan": [[], "https://cdn.frankerfacez.com/emoticon/167677/1"],
        // "Tuturu": [[], "https://cdn.frankerfacez.com/emoticon/25335/1"],
        // "Thonk": [[], "https://cdn.frankerfacez.com/emoticon/191246/1"],
        // "gachiBASS": [[], "https://cdn.frankerfacez.com/emoticon/273779/1"],
        // "MikuStare": [[], "https://cdn.frankerfacez.com/emoticon/229996/1"],
        // "PressF": [[], "https://cdn.frankerfacez.com/emoticon/28798/1"],
        // "PepeLmao": [[], "https://cdn.frankerfacez.com/emoticon/214658/1"],
        // "pepeJAM": [[], "https://cdn.frankerfacez.com/emoticon/341427/1"],
        // "SmileW": [[], "https://cdn.frankerfacez.com/emoticon/179088/1"],
        // "WaitWhat": [[], "https://cdn.frankerfacez.com/emoticon/47416/1"],
        // "peepoLove": [[], "https://cdn.frankerfacez.com/emoticon/250614/1"],
        // "EHEHE": [[], "https://cdn.frankerfacez.com/emoticon/101094/1"],
        // "SuchMeme": [[], "https://cdn.frankerfacez.com/emoticon/27825/1"],
        // "OhISee": [[], "https://cdn.frankerfacez.com/emoticon/230001/1"],
        // "POOGERS": [[], "https://cdn.frankerfacez.com/emoticon/240443/1"],
        // "PepoG": [[], "https://cdn.frankerfacez.com/emoticon/218530/1"],
        // "FeelsAmazingMan": [[], "https://cdn.frankerfacez.com/emoticon/119883/1"],
        // "nepSmug": [[], "https://cdn.frankerfacez.com/emoticon/151481/1"],
        // "monkaGIGA": [[], "https://cdn.frankerfacez.com/emoticon/183221/1"],
        // "Clap": [[], "https://cdn.frankerfacez.com/emoticon/298847/1"],
        // "pikachuS": [[], "https://cdn.frankerfacez.com/emoticon/298485/1"],
        // "peepoClown": [[], "https://cdn.frankerfacez.com/emoticon/318914/1"],
        // "SillyChamp": [[], "https://cdn.frankerfacez.com/emoticon/368150/1"],
        // "TooLewd": [[], "https://cdn.frankerfacez.com/emoticon/229999/1"],
        // "Pepepains": [[], "https://cdn.frankerfacez.com/emoticon/227992/1"],
        // "KKona": [[], "https://cdn.frankerfacez.com/emoticon/167498/1"],
        // "StrimPlz": [[], "https://cdn.frankerfacez.com/emoticon/36318/1"],
        // "Hahaa": [[], "https://cdn.frankerfacez.com/emoticon/57611/1"],
        // "ricardoFlick": [[], "https://cdn.frankerfacez.com/emoticon/303559/1"],
        // "FeelsWeirdManW": [[], "https://cdn.frankerfacez.com/emoticon/208616/1"],
        // "KannaNom": [[], "https://cdn.frankerfacez.com/emoticon/310289/1"],
        // "2Head": [[], "https://cdn.frankerfacez.com/emoticon/294078/1"],
        // "PLEASENO": [[], "https://cdn.frankerfacez.com/emoticon/229368/1"],
        // "BootyTime": [[], "https://cdn.frankerfacez.com/emoticon/22080/1"],
        // "PauseChamp": [[], "https://cdn.frankerfacez.com/emoticon/349048/1"],
        // "peepoWTF": [[], "https://cdn.frankerfacez.com/emoticon/267880/1"],
        // "eShrug": [[], "https://cdn.frankerfacez.com/emoticon/107715/1"],
        // "Daijoubu": [[], "https://cdn.frankerfacez.com/emoticon/229993/1"],
        // "4Shrug": [[], "https://cdn.frankerfacez.com/emoticon/226912/1"],
        // "POGGIES": [[], "https://cdn.frankerfacez.com/emoticon/257284/1"],
        // "Dolan": [[], "https://cdn.frankerfacez.com/emoticon/25933/1"],
        // "peepoFat": [[], "https://cdn.frankerfacez.com/emoticon/288800/1"],
        // "WutFaceW": [[], "https://cdn.frankerfacez.com/emoticon/168065/1"],
        // "monkaSpeed": [[], "https://cdn.frankerfacez.com/emoticon/260557/1"],
        // "PillowNo": [[], "https://cdn.frankerfacez.com/emoticon/235238/1"],
        // "PillowYes": [[], "https://cdn.frankerfacez.com/emoticon/235239/1"],
        // "RNGplz": [[], "https://cdn.frankerfacez.com/emoticon/30469/1"],
        // "PepeREE": [[], "https://cdn.frankerfacez.com/emoticon/197689/1"],
        // "pepeL": [[], "https://cdn.frankerfacez.com/emoticon/200804/1"],
        // "FacePalm": [[], "https://cdn.frankerfacez.com/emoticon/70179/1"],
        // "PainsChamp": [[], "https://cdn.frankerfacez.com/emoticon/263297/1"],
        // "SmugPepe": [[], "https://cdn.frankerfacez.com/emoticon/12042/1"],
        // "pepeGun": [[], "https://cdn.frankerfacez.com/emoticon/201244/1"],
        // "AYAYAY": [[], "https://cdn.frankerfacez.com/emoticon/250475/1"],
        // "FeelsBirthdayMan": [[], "https://cdn.frankerfacez.com/emoticon/52846/1"],
        // "peepoHug": [[], "https://cdn.frankerfacez.com/emoticon/237403/1"],
        // "KannaPolice": [[], "https://cdn.frankerfacez.com/emoticon/201877/1"],
        // "VaN": [[], "https://cdn.frankerfacez.com/emoticon/269928/1"],
        // "monkaT": [[], "https://cdn.frankerfacez.com/emoticon/209084/1"],
        // "peepoPog": [[], "https://cdn.frankerfacez.com/emoticon/302472/1"],
        // "4Weird": [[], "https://cdn.frankerfacez.com/emoticon/308193/1"],
        // "ConcernFroge": [[], "https://cdn.frankerfacez.com/emoticon/121482/1"],
        // "FeelsRageMan": [[], "https://cdn.frankerfacez.com/emoticon/53418/1"],
        // "PogCena": [[], "https://cdn.frankerfacez.com/emoticon/38540/1"],
        // "BibleBag": [[], "https://cdn.frankerfacez.com/emoticon/20706/1"],
        // "monkaChrist": [[], "https://cdn.frankerfacez.com/emoticon/243681/1"],
        // "4Heed": [[], "https://cdn.frankerfacez.com/emoticon/242432/1"],
        // "RoWOW": [[], "https://cdn.frankerfacez.com/emoticon/307977/1"],
        // "peepoRIP": [[], "https://cdn.frankerfacez.com/emoticon/244026/1"],
        // "WeebsOut": [[], "https://cdn.frankerfacez.com/emoticon/273365/1"],
        // "noxSorry": [[], "https://cdn.frankerfacez.com/emoticon/142957/1"],
        // "TooGood": [[], "https://cdn.frankerfacez.com/emoticon/230000/1"],
        // "peepoPoo": [[], "https://cdn.frankerfacez.com/emoticon/307828/1"],
        // "FeelsGladMan": [[], "https://cdn.frankerfacez.com/emoticon/69627/1"],
        // "POI": [[], "https://cdn.frankerfacez.com/emoticon/229122/1"],
        // "DesuOP": [[], "https://cdn.frankerfacez.com/emoticon/6490/1"],
        // "PeepoGlad": [[], "https://cdn.frankerfacez.com/emoticon/244322/1"],
        // "Catgasm": [[], "https://cdn.frankerfacez.com/emoticon/40837/1"],
        // "monkaThink": [[], "https://cdn.frankerfacez.com/emoticon/201690/1"],
        // "WanWan": [[], "https://cdn.frankerfacez.com/emoticon/25551/1"],
        // "FeelsSadMan": [[], "https://cdn.frankerfacez.com/emoticon/132030/1"],
        // "NyanPasu": [[], "https://cdn.frankerfacez.com/emoticon/34318/1"],
        // "COGGERS": [[], "https://cdn.frankerfacez.com/emoticon/250618/1"],
        // "Pogomega": [[], "https://cdn.frankerfacez.com/emoticon/220711/1"],
        // "YuuBooty": [[], "https://cdn.frankerfacez.com/emoticon/51289/1"],
        // "DontBully": [[], "https://cdn.frankerfacez.com/emoticon/151133/1"],
        // "4WeirdW": [[], "https://cdn.frankerfacez.com/emoticon/325413/1"],
        // "ToroSalt": [[], "https://cdn.frankerfacez.com/emoticon/35752/1"],
        // "NepYay": [[], "https://cdn.frankerfacez.com/emoticon/39656/1"],
        // "noxWhat": [[], "https://cdn.frankerfacez.com/emoticon/142956/1"],
        // "WTFF": [[], "https://cdn.frankerfacez.com/emoticon/241298/1"],
        // "TeeHee": [[], "https://cdn.frankerfacez.com/emoticon/151637/1"],
        // "KeK": [[], "https://cdn.frankerfacez.com/emoticon/265914/1"],
        // "NiceHost": [[], "https://cdn.frankerfacez.com/emoticon/81451/1"],
        // "Bruh": [[], "https://cdn.frankerfacez.com/emoticon/294111/1"],
        // "Magoo": [[], "https://cdn.frankerfacez.com/emoticon/27041/1"],
        // "Chag": [[], "https://cdn.frankerfacez.com/emoticon/243296/1"],
        // "GAMEOVER": [[], "https://cdn.frankerfacez.com/emoticon/26694/1"],
        // "HEYYEYAAEYAAAEYAEYAA": [[], "https://cdn.frankerfacez.com/emoticon/49777/1"],
        // "ThinkingFaceEmoji": [[], "https://cdn.frankerfacez.com/emoticon/118036/1"],
        // "AndKnuckles": [[], "https://cdn.frankerfacez.com/emoticon/24999/1"],
        // "GoodNight": [[], "https://cdn.frankerfacez.com/emoticon/75688/1"],
        // "PeepoWeird": [[], "https://cdn.frankerfacez.com/emoticon/243682/1"],
        // "PassTheBleach": [[], "https://cdn.frankerfacez.com/emoticon/40284/1"],
        // "4Gitte": [[], "https://cdn.frankerfacez.com/emoticon/249850/1"],
        // "HYPERDANSGAMEW": [[], "https://cdn.frankerfacez.com/emoticon/242861/1"],
        // "CosmicBrain": [[], "https://cdn.frankerfacez.com/emoticon/181164/1"],
        // "ABABABABA": [[], "https://cdn.frankerfacez.com/emoticon/82321/1"],
        // "monkaO": [[], "https://cdn.frankerfacez.com/emoticon/165806/1"],
        // "PogChomp": [[], "https://cdn.frankerfacez.com/emoticon/259795/1"],
        // "AYAYAHyper": [[], "https://cdn.frankerfacez.com/emoticon/278206/1"],
        // "GoodMorning": [[], "https://cdn.frankerfacez.com/emoticon/75689/1"],
        // "RunOgre": [[], "https://cdn.frankerfacez.com/emoticon/25321/1"],
        // "KEKWait": [[], "https://cdn.frankerfacez.com/emoticon/390750/1"],
        // "ILuvU": [[], "https://cdn.frankerfacez.com/emoticon/17914/1"],
        // "TriEasy": [[], "https://cdn.frankerfacez.com/emoticon/25122/1"],
        // "peepoCheer": [[], "https://cdn.frankerfacez.com/emoticon/217349/1"],
        // "KermitComfy": [[], "https://cdn.frankerfacez.com/emoticon/47941/1"],
        // "LurkMode": [[], "https://cdn.frankerfacez.com/emoticon/38914/1"],
        // "gachiPRIDE": [[], "https://cdn.frankerfacez.com/emoticon/147553/1"],
        // "LickMe": [[], "https://cdn.frankerfacez.com/emoticon/28453/1"],
        // "PoiPoi": [[], "https://cdn.frankerfacez.com/emoticon/29072/1"],
        // "BOOMER": [[], "https://cdn.frankerfacez.com/emoticon/316078/1"],
        // "YeahBoi": [[], "https://cdn.frankerfacez.com/emoticon/43360/1"],
        // "KermitENOUGH": [[], "https://cdn.frankerfacez.com/emoticon/134065/1"],
        // "peepoPooPoo": [[], "https://cdn.frankerfacez.com/emoticon/313588/1"],
        // "HyperLUL": [[], "https://cdn.frankerfacez.com/emoticon/167825/1"],
        // "xbn": [[], "https://cdn.frankerfacez.com/emoticon/1383/1"],
        // "WoweeW": [[], "https://cdn.frankerfacez.com/emoticon/181160/1"],
        // "RAGEY": [[], "https://cdn.frankerfacez.com/emoticon/263587/1"],
        // "pepoHmm": [[], "https://cdn.frankerfacez.com/emoticon/204804/1"],
        // "Kermitpls": [[], "https://cdn.frankerfacez.com/emoticon/33947/1"],
        // "monkaSSS": [[], "https://cdn.frankerfacez.com/emoticon/201363/1"],
        // "MeguminHappy": [[], "https://cdn.frankerfacez.com/emoticon/85103/1"],
    }
};
