import {SetData} from "./index";
import { browser } from "webextension-polyfill-ts";

const lichessSetData: SetData = {
    "name": "Lichess",
    "iconUrl": browser.runtime.getURL('assets/images/lichess_icon512.png'),
    "font": {
        fontFamily: 'lichess',
        src: `url(${browser.runtime.getURL('assets/fonts/lichess.woff2')} format("woff2")`,
    },
    "tags": {
        "exit": ["\ue024"],
        "tv": ["\ue025"],
        // "hand-top": ["2"], // unused after an update
        "wifi": ["\ue026"],
        "delicious": ["\ue027"],
        "shield": ["\ue028"],
        "inkPen": ["\ue029"],
        "target": ["\ue02a"],
        "crown": ["\ue02b"],
        "chart-line": ["\ue02c"],
        "lock": ["\ue054"],
        "white-flag": ["\ue055"],
        "dialog-bubble": ["\ue056"],
        "dialog-bubbles": ["\ue057"],
        "letter": ["\ue058"],
        "crowd": ["\ue059"],
        "goblet": ["\ue05a", ["variant"]],
        "thumb-up": ["\ue05b"],
        "arrow-loop-left": ["\ue05c"],
        "exclamation": ["\ue05d"],
        "not-allowed": ["\ue05e"],
        "pen": ["\ue060"],
        "tag": ["\ue062"],
        "clock": ["\ue063"],
        "trash-bin": ["\ue064"],
        "human": ["\ue065"],
        "star": ["\ue066"],
        "full-star": ["\ue067"],
        "eye": ["\ue069"],
        "power-button": ["\ue06a"],
        "search-find": ["\ue06c"],
        "arrow-loop-right": ["\ue06d"],
        "microscope": ["\ue034"],
        "loop": ["\ue035"],
        "crown-king": ["\ue036"],
        "check": ["\ue038"],
        "leave": ["\ue039"],
        "circle-full": ["\ue03d"],
        "circle": ["\ue03e"],
        "cancel": ["\ue03f"],
        "arrow-left-down": ["\ue040"],
        "arrow-right-up": ["\ue041"],
        "plus": ["\ue042"],
        "arrow-loop": ["\ue043"],
        "burning-fire": ["\ue044"],
        "arrow-down": ["\ue045"],
        "arrow-up": ["\ue046"],
        "lightning": ["\ue047"],
        "crossed-swords": ["\ue048"],
        "pause": ["\ue04d"],
        "antichess": ["\ue033", ["variant"]],
        "rabbit": ["\ue017", ["rapid"]],
        "turtle": ["\ue01f", ["classic", "slow"]],
        "repo": ["\ue01a", ["repository"]],
        "feather": ["\ue01e"],
        "flag": ["\ue01c"],
        "flame": ["\ue01d", ["blitz"]],
        "book": ["\ue050", ["repo"]],
        "link": ["\ue016", ["chain"]],
        "die-six": ["\ue018", ["die", "dice", "960", "chess960", "variant"]],
        "nuclear": ["\ue031"],
        "arrow-streamline-target": ["\ue021"],
        "buffer": ["\ue022", ["threecheck", "variant"]],
        "upload-cloud": ["\ue023"],
        "pointer": ["\ue06e", ["ultrabullet", "variant"]],
        "hookah": ["\ue011", ["bongcloud"]],
        "berserk": ["\ue053"],
        "graph": ["\ue02c"],
        "graduate-cap": ["\ue02d"],
        "plane": ["\ue02e"],
        "zoom-in": ["\ue02f"],
        "atomic": ["\ue031", ["variant"]],
        "screen": ["\ue030"]
    }
};

export default lichessSetData;
